services:
  - type: web
    name: aadhaar-qr
    env: node
    buildCommand: npm run install-py-deps && npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    packages:
      - python3-pip
      - python3-dev
      - libzbar0
      - libzbar-dev
      - python3-opencv