services:
  - type: web
    name: aadhaar-qr
    runtime: node
    region: singapore
    plan: free
    buildCommand: apt-get update -y && apt-get install -y python3-pip python3-dev libzbar0 libzbar-dev python3-opencv zbar-tools && python3 -m pip install -r requirements.txt && npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true