services:
  - type: web
    name: aadhaar-qr
    runtime: node
    region: singapore
    plan: free
    buildCommand: |
      # Install Python and pip using pyenv
      curl https://pyenv.run | bash
      export PATH="$HOME/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
      pyenv install 3.11.0
      pyenv global 3.11.0
      
      # Install Python dependencies in user space
      python3 -m pip install --user --no-cache-dir -r requirements.txt
      
      # Build the Node.js app
      npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PATH
        value: $HOME/.local/bin:$PATH
    autoDeploy: true