services:
  - type: web
    name: aadhaar-qr
    env: node
    buildCommand: |
      # Install system packages first
      apt-get update -y && \
      apt-get install -y \
        python3-pip \
        python3-dev \
        libzbar0 \
        libzbar-dev \
        python3-opencv \
        zbar-tools && \
      # Then install Python dependencies
      python3 -m pip install --upgrade pip && \
      python3 -m pip install -r requirements.txt && \
      # Finally build the Node.js app
      npm ci && \
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0